Q1. Create two 3×3 matrices using the random function in Numpy and perform the following operations.
è Product (prod)
è Multiplication (multiply)
è Dot Product (dot)


In [19]:
import numpy as np

# Create two 3x3 matrices
mat1 = np.random.randint(10, size=(3,3))
mat2 = np.random.randint(10, size=(3,3))

print("matrix-1")
print(mat1)
print("matrix-2")
print(mat2)

# Product (prod)
product = np.matmul(mat1, mat2)
print("Product of the matrices:")
print(product)

# Multiplication (multiply)
multiplication = mat1 * mat2
print("Multiplication of the matrices:")
print(multiplication)

# Dot product (dot)
dot_product = np.dot(mat1, mat2)
print("Dot product of the matrices:")
print(dot_product)

matrix-1
[[0 7 9]
 [6 5 6]
 [0 6 9]]
matrix-2
[[6 2 6]
 [8 6 4]
 [1 2 0]]
Product of the matrices:
[[65 60 28]
 [82 54 56]
 [57 54 24]]
Multiplication of the matrices:
[[ 0 14 54]
 [48 30 24]
 [ 0 12  0]]
Dot product of the matrices:
[[65 60 28]
 [82 54 56]
 [57 54 24]]


Q2. Perform the following set operations using the Numpy functions.
è Union
è Intersection
è Set difference
è XOR


In [20]:
import numpy as np

# Create two sets
set1 = np.array([1, 2, 3, 4, 5])
set2 = np.array([3, 4, 5, 6, 7])

# Union
union = np.union1d(set1, set2)
print("Union of the sets:")
print(union)

# Intersection
intersection = np.intersect1d(set1, set2)
print("Intersection of the sets:")
print(intersection)

# Set difference
difference = np.setdiff1d(set1, set2)
print("Set difference of the sets:")
print(difference)

# XOR
xor = np.setxor1d(set1, set2)
print("XOR of the sets:")
print(xor)

Union of the sets:
[1 2 3 4 5 6 7]
Intersection of the sets:
[3 4 5]
Set difference of the sets:
[1 2]
XOR of the sets:
[1 2 6 7]


Q3. Create a 1D array using Random function and perform the following operations.
è Cumulative sum
è Cumulative Product
è Discrete difference (with n=3)
è Find the unique elements from the array


In [21]:
import numpy as np

# Create a 1D array with 10 elements
arr = np.random.randint(1, 10, 10)

# Cumulative sum
cumsum = np.cumsum(arr)
print("Cumulative sum of the array:")
print(cumsum)

# Cumulative product
cumprod = np.cumprod(arr)
print("Cumulative product of the array:")
print(cumprod)

# Discrete difference (with n=3)
diff = np.diff(arr, n=3)
print("Discrete difference of the array (with n=3):")
print(diff)

# Find the unique elements from the array
unique_elements = np.unique(arr)
print("Unique elements from the array:")
print(unique_elements)

Cumulative sum of the array:
[ 8  9 18 19 25 26 35 44 49 53]
Cumulative product of the array:
[     8      8     72     72    432    432   3888  34992 174960 699840]
Discrete difference of the array (with n=3):
[-31  29 -23  23 -21   4   7]
Unique elements from the array:
[1 4 5 6 8 9]


Q4. Create two 1D array and perform the Addition using zip(), add() and user defined function (frompyfunc())


In [22]:
import numpy as np

# Create two 1D arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

# Addition using zip() and add()
def add_func(a, b):
  return a + b

addition_using_zip_and_add = np.frompyfunc(add_func, 2, 1)(arr1, arr2)
print("Addition using zip() and add():")
print(addition_using_zip_and_add)

# Addition using user defined function
def my_add_func(a, b):
  return a + b

addition_using_user_defined_function = np.vectorize(my_add_func)(arr1, arr2)
print("Addition using user defined function:")
print(addition_using_user_defined_function)

Addition using zip() and add():
[7 9 11 13 15]
Addition using user defined function:
[ 7  9 11 13 15]


Q5. Find the LCM (Least Common Multiple) and GCD (Greatest Common Divisor) of an array of elements using reduce().


In [23]:
import numpy as np
from functools import reduce

# Create an array of elements
arr = np.array([1, 2, 3, 4, 5])

# Find the LCM using reduce()
def lcm(a, b):
  return a * b // np.gcd(a, b)

lcm_of_arr = reduce(lcm, arr)
print("LCM of the array:", lcm_of_arr)

# Find the GCD using reduce()
def gcd(a, b):
  while b:
    a, b = b, a % b
  return a

gcd_of_arr = reduce(gcd, arr)
print("GCD of the array:", gcd_of_arr)

LCM of the array: 60
GCD of the array: 1
