Q1. Write a program to distinguish between Array Indexing and Fancy Indexing.

In [18]:
import numpy as np

# Creating a sample 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Array Indexing
print("Array Indexing:")
print(arr[0, 1])  # Accessing a single element at row 0, column 1
print(arr[2, 2])  # Accessing a single element at row 2, column 2

# Fancy Indexing
print("\nFancy Indexing:")
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])
print(arr[row_indices, col_indices])  # Accessing elements using arrays of indices


Array Indexing:
2
9

Fancy Indexing:
[2 6 7]


Q2. Execute the 2D array Slicing.

In [19]:
import numpy as np

# Creating a sample 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Slicing
print("Sliced array:")
print(arr[0:2, 1:3])  # Slicing rows 0 to 1 and columns 1 to 2


Sliced array:
[[2 3]
 [5 6]]


Q3. Create the 5-Dimensional arrays using ‘ndmin’.

In [20]:
import numpy as np

# Creating a 5-D array with ndmin
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)


[[[[[1 2 3 4]]]]]


Q4. Reshape the array from 1-D to 2-D array.

In [21]:
import numpy as np

# Creating a 1-D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshaping to a 2-D array
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)


[[1 2 3]
 [4 5 6]]


Q5. Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack().

In [22]:
import numpy as np

# Creating sample arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stack vertically
vstacked = np.vstack((arr1, arr2))
print("Vertical Stack:")
print(vstacked)

# Stack horizontally
hstacked = np.hstack((arr1, arr2))
print("\nHorizontal Stack:")
print(hstacked)

# Stack along the third axis (depth)
dstacked = np.dstack((arr1, arr2))
print("\nDepth Stack:")
print(dstacked)

# Stack arrays along a new axis
stacked = np.stack((arr1, arr2), axis=0)
print("\nStack along New Axis:")
print(stacked)


Vertical Stack:
[[1 2 3]
 [4 5 6]]

Horizontal Stack:
[1 2 3 4 5 6]

Depth Stack:
[[[1 4]
  [2 5]
  [3 6]]]

Stack along New Axis:
[[1 2 3]
 [4 5 6]]


Q6. Perform the searchsort method in Numpy array.

In [23]:
import numpy as np

# Creating a sorted array
arr = np.array([1, 2, 4, 5, 7, 8])

# Using searchsorted to find the index where 3 would be inserted to maintain the sorted order
index = np.searchsorted(arr, 3)
print("Index for 3:", index)


Index for 3: 2


Q7. Create Numpy Structured array using your domain features.

In [24]:
import numpy as np

# Define structured data type with domain features
dtype = np.dtype([('name', 'S20'), ('age', int), ('score', float)])

# Create an empty structured array
data = np.array([], dtype=dtype)

# Adding data to the structured array
data = np.append(data, np.array([('Alice', 25, 92.5)], dtype=dtype))
data = np.append(data, np.array([('Bob', 30, 85.0)], dtype=dtype))

print("Structured Array:")
print(data)


Structured Array:
[(b'Alice', 25, 92.5) (b'Bob', 30, 85. )]


Q8. Create Data frame using List and Dictionary.

In [25]:
import pandas as pd

# Create a DataFrame using a list of dictionaries
data = [{'Name': 'Lahari', 'Age': 22},
        {'Name': 'priya', 'Age': 20},
        {'Name': 'likitha', 'Age': 21}]

df = pd.DataFrame(data)

# Create a DataFrame using a dictionary
data_dict = {'Name': ['Chris', 'Deepak', 'Clement'],
             'Age': [21, 21, 21]}

df_dict = pd.DataFrame(data_dict)

print("DataFrame using List of Dictionaries:")
print(df)

print("\nDataFrame using Dictionary:")
print(df_dict)


DataFrame using List of Dictionaries:
      Name  Age
0   Lahari   22
1    priya   20
2  likitha   21

DataFrame using Dictionary:
      Name  Age
0    Chris   21
1   Deepak   21
2  Clement   21


Q9. Create Data frame on your Domain area and perform the following operations to find and eliminate the
missing data from the dataset.
• isnull()
• notnull()
• dropna()
• fillna()
• replace()
• interpolate()

In [26]:
import pandas as pd
import numpy as np

# Create a sample DataFrame
data = {
    'Date': ['2023-09-01', '2023-09-02', '2023-09-03', '2023-09-04', '2023-09-05'],
    'MilkProduction(liters)': [100, np.nan, 120, 150, 110],
    'Temperature(Celsius)': [28, 30, np.nan, 29, 31],
    'Humidity(%)': [50, 55, 48, np.nan, 52]
}

df = pd.DataFrame(data)

# Find missing data
missing_data = df.isnull()
not_missing_data = df.notnull()

print("Missing Data:")
print(missing_data)

print("\nNot Missing Data:")
print(not_missing_data)

# Remove rows with missing data
df_no_missing = df.dropna()

print("\nDataFrame without Missing Data:")
print(df_no_missing)

# Fill missing values with 0
df_filled = df.fillna(0)

print("\nDataFrame with Missing Values Filled with 0:")
print(df_filled)

# Replace NaN with a custom value (e.g., -1)
df_replaced = df.replace(np.nan, -1)

print("\nDataFrame with NaN Replaced:")
print(df_replaced)

# Interpolate missing values
df_interpolated = df.interpolate()

print("\nDataFrame with Interpolated Missing Values:")
print(df_interpolated)


Missing Data:
    Date  MilkProduction(liters)  Temperature(Celsius)  Humidity(%)
0  False                   False                 False        False
1  False                    True                 False        False
2  False                   False                  True        False
3  False                   False                 False         True
4  False                   False                 False        False

Not Missing Data:
   Date  MilkProduction(liters)  Temperature(Celsius)  Humidity(%)
0  True                    True                  True         True
1  True                   False                  True         True
2  True                    True                 False         True
3  True                    True                  True        False
4  True                    True                  True         True

DataFrame without Missing Data:
         Date  MilkProduction(liters)  Temperature(Celsius)  Humidity(%)
0  2023-09-01                   100.0              

C:\Users\asus\AppData\Local\Temp\ipykernel_122040\2852805363.py:43: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_interpolated = df.interpolate()


Q10. Perform the Hierarchical Indexing in the above created dataset.

In [27]:
import pandas as pd
import numpy as np

# Create a sample DataFrame
data = {
    'Date': ['2023-09-01', '2023-09-02', '2023-09-03', '2023-09-04', '2023-09-05'],
    'MilkProduction(liters)': [100, np.nan, 120, 150, 110],
    'Temperature(Celsius)': [28, 30, np.nan, 29, 31],
    'Humidity(%)': [50, 55, 48, np.nan, 52]
}

df = pd.DataFrame(data)

# Perform Hierarchical Indexing
df.set_index(['Date', 'MilkProduction(liters)'], inplace=True)

# Display the DataFrame with Hierarchical Index
print(df)


                                   Temperature(Celsius)  Humidity(%)
Date       MilkProduction(liters)                                   
2023-09-01 100.0                                   28.0         50.0
2023-09-02 NaN                                     30.0         55.0
2023-09-03 120.0                                    NaN         48.0
2023-09-04 150.0                                   29.0          NaN
2023-09-05 110.0                                   31.0         52.0
